
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Afika.Shwashwa
 */
public class TaxCalculatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form TaxCalculatorFrame
     */
    public TaxCalculatorFrame() {
        initComponents();
    }

    double income;
    String Ouput;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ageSelection = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jbtnEnter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelTax = new javax.swing.JLabel();
        jLabelDisplay = new javax.swing.JLabel();
        jLabelDisplayIncome = new javax.swing.JLabel();
        jLabelMonthly = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rdUnder65 = new javax.swing.JRadioButton();
        rdInBetween = new javax.swing.JRadioButton();
        rdOver75 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jtxtIncome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TAX CALCULATOR");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fill in all the required fields to calculate your tax obligation");

        jbtnEnter.setBackground(new java.awt.Color(153, 153, 0));
        jbtnEnter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnEnter.setForeground(new java.awt.Color(0, 0, 0));
        jbtnEnter.setText("CALCULATE ");
        jbtnEnter.setToolTipText("");
        jbtnEnter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(51, 255, 51), new java.awt.Color(0, 255, 0), new java.awt.Color(0, 0, 255)));
        jbtnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEnterActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setEnabled(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTax.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTax.setText("__________________________");
        jPanel3.add(jLabelTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 170, -1));

        jLabelDisplay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDisplay.setText("__________________________");
        jPanel3.add(jLabelDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 180, -1));

        jLabelDisplayIncome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDisplayIncome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDisplayIncome.setText("__________________________");
        jPanel3.add(jLabelDisplayIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 170, -1));

        jLabelMonthly.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMonthly.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMonthly.setText("__________________________");
        jPanel3.add(jLabelMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tax :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Annual Income :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Monthly Tax :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Annual Tax obligation :");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(284, 112));

        ageSelection.add(rdUnder65);
        rdUnder65.setForeground(new java.awt.Color(255, 255, 255));
        rdUnder65.setText("Under 65");

        ageSelection.add(rdInBetween);
        rdInBetween.setForeground(new java.awt.Color(255, 255, 255));
        rdInBetween.setText("65-75");

        ageSelection.add(rdOver75);
        rdOver75.setForeground(new java.awt.Color(255, 255, 255));
        rdOver75.setText("Over 75");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("How old are you");
        jLabel5.setPreferredSize(new java.awt.Dimension(108, 16));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdUnder65)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(rdInBetween)
                .addGap(30, 30, 30)
                .addComponent(rdOver75)
                .addGap(14, 14, 14))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdOver75)
                    .addComponent(rdInBetween)
                    .addComponent(rdUnder65))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtxtIncome.setBackground(new java.awt.Color(51, 51, 51));
        jtxtIncome.setForeground(new java.awt.Color(255, 255, 255));
        jtxtIncome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxtIncome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtxtIncome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtxtIncomeMouseEntered(evt);
            }
        });
        jtxtIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIncomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Annual income before tax");

        jSeparator2.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtIncome, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxtIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("RESET");
        jButton1.setToolTipText("");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(0, 204, 0), new java.awt.Color(0, 204, 51), new java.awt.Color(0, 51, 255)));
        jButton1.setMaximumSize(new java.awt.Dimension(40, 22));
        jButton1.setMinimumSize(new java.awt.Dimension(40, 22));
        jButton1.setPreferredSize(new java.awt.Dimension(40, 22));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fantastic 4");
        jLabel4.setPreferredSize(new java.awt.Dimension(666, 375));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jbtnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))))
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnEnter, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tax_Calculator(String taxCal) {
//        String annualIncome = jtxtIncome.getText() + taxCal;
//
//        String display = jLabelDisplay.getText();
//        jLabelDisplay.setText(annualIncome);
//
    }

    private void jtxtIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIncomeActionPerformed

    private void jbtnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEnterActionPerformed
        try {
            income = Double.parseDouble(jtxtIncome.getText());
            double tax = 0;
            double taxPercentage = 0;
            double monthlyTax = 0;
            if (rdUnder65.isSelected()) {

                if (!jtxtIncome.getText().isEmpty()) {
                    if (income <= 95750) {
                        tax = 0; // No tax for negative or zero income
                        monthlyTax = tax / 12;

                    } else if (income >= 95751 && income <= 237100) {
                        taxPercentage = 0.18;
                        tax = income * taxPercentage - 17235;
                        monthlyTax = tax / 12;
                    } else if (income <= 370500) {
                        taxPercentage = 0.26;
                        tax = (42678 + (income * taxPercentage) - 78881); 
                        monthlyTax = tax / 12;
                    } else if (income <= 512800) {
                        taxPercentage = 0.31;
                        tax = (77362 + (income * taxPercentage) - 132090); 
                        monthlyTax = tax / 12;
                    } else if (income <= 673000) {
                        taxPercentage = 0.36;
                        tax = (121475 + (income * taxPercentage) - 201843);
                        monthlyTax = tax / 12;
                    } else if (income <= 857900) {
                        taxPercentage = 0.36;
                        tax = (179147 + (income * 0.39) - 255699.04); 
                        monthlyTax = tax / 12;
                    } else if (income <= 1817000) {
                        taxPercentage = 0.41;
                        tax = (251258 + (income * taxPercentage) - 368975);
                        monthlyTax = tax / 12;
                    } else {
                        taxPercentage = 0.45;
                        tax = (644489 + (income * taxPercentage));
                        monthlyTax = tax / 12;
                    }
                    
                    
                    double taxP = taxPercentage * 100;
                    jLabelTax.setText(String.valueOf(Math.round(taxP)) + "%");
                    jLabelMonthly.setText("R" + String.valueOf(Math.round(monthlyTax)));
                    jLabelDisplayIncome.setText("R" + String.valueOf(Math.round(income)));
                    jLabelDisplay.setText("R" + String.valueOf(Math.round(tax)) + "pa");
                    jtxtIncome.setText("");
                }
            } else if (rdInBetween.isSelected()) {

                if (!jtxtIncome.getText().isEmpty()) {
                    if (income <= 148217) {
                        tax = 0; // No tax for negative or zero income
                        monthlyTax = tax / 12;

                    } else if (income >= 148218 && income <= 237210) {
                        taxPercentage = 0.18;
                        tax = income * taxPercentage - 26679; 
                        monthlyTax = tax / 12;
                    } else if (income <= 370500) {
                        taxPercentage = 0.26;
                        tax = (42678 + (income * taxPercentage) - 88325); 
                        monthlyTax = tax / 12;
                    } else if (income <= 515000) {
                        taxPercentage = 0.31;
                        tax = (77362 + (income * taxPercentage) - 141534); 
                        monthlyTax = tax / 12;
                    } else if (income <= 672000) {
                        taxPercentage = 0.36;
                        tax = (121475 + (income * taxPercentage) - 211287); 
                        monthlyTax = tax / 12;
                    } else if (income <= 860000) {
                        taxPercentage = 0.39;
                        tax = (179147 + (income * taxPercentage) - 289149);
                        monthlyTax = tax / 12;
                    } else if (income <= 1817000) {
                        taxPercentage = 0.41;
                        tax = (251258 + (income * taxPercentage) - 378418);
                        monthlyTax = tax / 12;
                    } else {
                        taxPercentage = 0.45;
                        tax = (644489 + (income * taxPercentage));
                        monthlyTax = tax / 12;
                    }
                    double taxP = taxPercentage * 100;
                    jLabelTax.setText(String.valueOf(Math.round(taxP)) + "%");
                    jLabelMonthly.setText("R" + String.valueOf(Math.round(monthlyTax)));
                    jLabelDisplayIncome.setText("R" + String.valueOf(Math.round(income)));
                    jLabelDisplay.setText("R" + String.valueOf(Math.round(tax)) + "pa");
                    jtxtIncome.setText("");
                }
            } else if (rdOver75.isSelected()) {

                if (!jtxtIncome.getText().isEmpty()) {
                    if (income <= 165689) {
                        tax = 0; // No tax for negative or zero income
                        monthlyTax = tax / 12;

                    } else if (income >= 165690 && income <= 237100) {
                        taxPercentage = 0.18;
                        tax = income * taxPercentage - 29824; 
                        monthlyTax = tax / 12;
                    } else if (income <= 370500) {
                        taxPercentage = 0.26;
                        tax = (42678 + (income * taxPercentage) - 91470); 
                        monthlyTax = tax / 12;
                    } else if (income <= 512800) {
                        taxPercentage = 0.31;
                        tax = (77362 + (income * taxPercentage) - 144679); 
                        monthlyTax = tax / 12;
                    } else if (income <= 672000) {
                        taxPercentage = 0.36;
                        tax = (121475 + (income * taxPercentage) - 214432); 
                        monthlyTax = tax / 12;
                    } else if (income <= 858000) {
                        taxPercentage = 0.39;
                        tax = (179147 + (income * taxPercentage) - 292294); 
                        monthlyTax = tax / 12;
                    } else if (income <= 1817000) {
                        taxPercentage = 0.41;
                        tax = (251258 + (income * taxPercentage) - 381563); 
                        monthlyTax = tax / 12;
                    } else {
                        taxPercentage = 0.45;
                        tax = (644489 + (income * taxPercentage)); 
                        monthlyTax = tax / 12;
                    }
                    double taxP = taxPercentage * 100;
                    jLabelTax.setText(String.valueOf(Math.round(taxP)) + "%");
                    jLabelMonthly.setText("R" + String.valueOf(Math.round(monthlyTax)));
                    jLabelDisplayIncome.setText("R" + String.valueOf(Math.round(income)));
                    jLabelDisplay.setText("R" + String.valueOf(Math.round(tax)) + "pa");
                    jtxtIncome.setText("");
                }
            } else {
                jLabelTax.setText("__________________________");
                jLabelMonthly.setText("__________________________");
                jLabelDisplayIncome.setText("__________________________");
                jLabelDisplay.setText("__________________________");
                JOptionPane.showMessageDialog(rootPane, "Invalid input! \n\nPlease select your Age");
            }

        } catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(rootPane, "Invalid input! \n\nEnter a valid amount!");
        }


    }//GEN-LAST:event_jbtnEnterActionPerformed

    private void jtxtIncomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIncomeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIncomeMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabelTax.setText("__________________________");
        jLabelMonthly.setText("__________________________");
        jLabelDisplayIncome.setText("__________________________");
        jLabelDisplay.setText("__________________________");
        rdUnder65.setSelected(true);
        rdInBetween.setSelected(false);
        rdOver75.setSelected(false);
            jtxtIncome.setText("");    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaxCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaxCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaxCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaxCalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaxCalculatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ageSelection;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDisplay;
    private javax.swing.JLabel jLabelDisplayIncome;
    private javax.swing.JLabel jLabelMonthly;
    private javax.swing.JLabel jLabelTax;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnEnter;
    private javax.swing.JTextField jtxtIncome;
    private javax.swing.JRadioButton rdInBetween;
    private javax.swing.JRadioButton rdOver75;
    private javax.swing.JRadioButton rdUnder65;
    // End of variables declaration//GEN-END:variables
}
